apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  labels:
    app.kubernetes.io/component: models-web-app
  name: kserve-models-web-app
spec:
  action: ALLOW
  selector:
    matchLabels:
      app.kubernetes.io/component: models-web-app
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account
