apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - virtual-service.yaml
  - authorization-policy.yaml

patches:
  - path: web-app-sidecar.yaml

labels:
  - pairs:
      app.kubernetes.io/component: models-web-app
